### ISSUE TITLE
Update the content of the website

### ISSUE THREAD

**Issue by tvercaut** [learn2reg/learn2reg.github.io#3]
Adding a new item to the "Recent Updates" to highlight that the slides and tutorials are now available on github would be great.

Also, we need to update the url in
```
Tutorials will be available on github. 
```

**Comment by Khoa-NT** [comment]
Hi, 
I would like to ask where are the slides and tutorials in this repo ?

**Comment by YipengHu** [comment]
Hi @adalca ,

I don't seem to be able to update the website. If you give me the permission, I'll update these.

Yipeng

**Comment by YipengHu** [comment]
@shaolinkhoa everything is here: https://github.com/learn2reg/tutorials2019

**Comment by Khoa-NT** [comment]
@YipengHu thank you.

**Comment by adalca** [comment]
@YipengHu , you should have the right permissions when logged in, you're a full collaborator!

I made the changes suggested above.
